### ISSUE TITLE
Is cert file required ?

### ISSUE THREAD

**Issue by Gustry** [edgd1er/jeedom-rpi#1]
Thanks for this repository.

According to readme : 
https://github.com/edgd1er/jeedom-rpi/blob/master/README.md#installation

Steps 1 to 4 doesn't mention cert files.
Maybe I'm wrong, but the docker-compose stack doesn't boot because of missing files when following steps 1 to 4 : 

```
etienne@embrun:~/jeedom-rpi $ docker-compose up --build
jeedom-rpi_mysql_1 is up-to-date
Starting jeedom-rpi_web_1 ... error

ERROR: for jeedom-rpi_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/etienne/jeedom-rpi/cert.pem" to rootfs at "/var/lib/docker/overlay2/7fc80947e8a51513e09153efbb7fb5648c4482f1c0f9df797687022d51db623f/merged/etc/ssl/certs/ssl-cert-snakeoil.pem" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/etienne/jeedom-rpi/cert.pem" to rootfs at "/var/lib/docker/overlay2/7fc80947e8a51513e09153efbb7fb5648c4482f1c0f9df797687022d51db623f/merged/etc/ssl/certs/ssl-cert-snakeoil.pem" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
etienne@embrun:~/jeedom-rpi $ 
```

Thanks for any advice.

**Comment by edgd1er** [comment]
Hi @Gustry 

Sorry for the late aknowledgmenent. Certs files are not required. If not provided, default snake-oil certs will be set and the container will be exposed on ports 9443 with theses certs. If you want to define yours, then the docker-compose file is ready.

That part of the readme might be a bit confusing.

**Comment by Gustry** [comment]
Apparently, my docker-compose was failing (error message above) without cert files.

Maybe I was wrong, I'm closing. Thanks for your inputs.

**Comment by edgd1er** [comment]
I would say that when starting the container with no certs file while certs files are present in the yaml file, docker-compose will create them as directories.

I guess you have now a cert.pem and cert.ssl  directories in /home/etienne/jeedom-rpi/

you may try to comment as hereunder theses lines in your docker-compose.yaml.
# only needed if you want to set your own certificate.
      #- ./cert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      #- ./privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro

**Comment by Gustry** [comment]
I don't have access to the raspberry pi right now so I can't try.

I have generated the cert file in the meantime so for me now it's ok.
