### ISSUE TITLE
Compatibilty with raspberry pi v4

### ISSUE THREAD

**Issue by naonak** [edgd1er/jeedom-rpi#15]
Hello,

It should be great to make it work with linux/arm64/v8

Thanks for your work

**Comment by edgd1er** [comment]
Hello,

Sorry just realized now about the issue. I may add this platform to the build, but i don t have a rpi installed with arm64 os. 
When built, could you confirm it s ok

**Comment by naonak** [comment]
Hello, Ok I will test that. Thanks !

**Comment by naonak** [comment]
That work with my raspberry pi v4, thanks !
